name: Check Course Availability

on:
  schedule:
    - cron: '*/15 3-20 * * *'  # Runs every 15 minutes between 6:00 to 23:59 EAT
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'  # This enables npm caching
      
      - name: Install dependencies
        run: npm ci  # Use npm ci instead of npm install in CI environments
      
      - name: Run course checker
        run: node course_checker.js
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} 